<?php
/**
 * 快递100查询接口
 * Created by PhpStorm.
 * User: jory
 * Date: 2019/1/7
 * Time: 9:00
 */

namespace Modules\Core\Utils;


class KuaiDi
{

    const API_HOST = 'http://www.kuaidi100.com';
    const API_GUEST_NAME = self::API_HOST.'/autonumber/auto';
    const API_QUERY = self::API_HOST.'/poll/query.do';
    const API_POLL_REGISTER = 'https://poll.kuaidi100.com/poll';

    /**
     * 猜测快递代码
     * @param $num
     * @return mixed
     */
    public function guestName($num)
    {
        $query = http_build_query([
            'key' => config('kuaidi100.guest_code.key'),
            'num' => $num
        ]);
        $http = new \GuzzleHttp\Client();
        $response = $http->get(self::API_GUEST_NAME, ['query' => $query]);
        $res = json_decode($response->getBody()->getContents(), true);
        $name = self::numCode()->where('code', $res[0]['comCode'])->first();
        return array_merge($res[0], $name);
    }


    /**
     * 查询快递
     * @param $num
     * @param $nameCode
     * @return mixed
     */
    public static function search($num, $name)
    {
        $cache_key = 'kuaidi_'.$num;
        $res = cache($cache_key);

        if(!$res) {
            $nameMap = self::numCode()->where('name', $name)->first();
            if(!$nameMap) {
                return false;
            }
            $post_data["param"] = json_encode([
                'num' => $num,
                'com' => $nameMap['code']
            ]);
            $key = config('kuaidi100.search.key');
            $post_data['customer'] = config('kuaidi100.search.customer');

            $post_data["sign"] = md5($post_data["param"].$key.$post_data["customer"]);
            $post_data["sign"] = strtoupper($post_data["sign"]);

            $http = new \GuzzleHttp\Client();
            $response = $http->post(self::API_QUERY, ['form_params' => $post_data]);
            $res = json_decode($response->getBody()->getContents(), true);

            cache([$cache_key => $res], 600);
        }
        return $res;
    }

//    public function registerPoll()
//    {
//        $post_data = json_encode([
//            'schema' => 'JSON',
//            'param' => [
//                'company' => '',
//                'number' => '',
//                'key' => '',
//                'parameters' => [
//                    'callbackurl' => '',
//                    'salt' => '',
//                    ''
//                ]
//            ]
//        ]);
//    }

    /**
     * @param $code
     * @return string
     */
    public static function getCompany($code)
    {
        $res = '';
        foreach (self::numCode() as $_code) {
            if($_code['code'] == $code) {
                $res = $_code['name'];
                break;
            }
        }
        return $res;
    }

    /**
     * @return array
     */
    public static function numCode()
    {
        return collect([
            array('name' => '中通快递','code' => 'zhongtong'),
            array('name' => '圆通速递','code' => 'yuantong'),
            array('name' => '申通快递','code' => 'shentong'),
            array('name' => '顺丰速运','code' => 'shunfeng'),
            array('name' => 'EMS','code' => 'ems'),
            array('name' => '宅急送','code' => 'zhaijisong'),
            array('name' => '京东物流','code' => 'jd'),
            array('name' => '天天快递','code' => 'tiantian'),
            array('name' => '金岸物流','code' => 'jinan'),
            array('name' => '海带宝','code' => 'haidaibao'),
            array('name' => '澳通华人物流','code' => 'cllexpress'),
            array('name' => '斑马物流','code' => 'banma'),
            array('name' => '信丰物流','code' => 'xinfengwuliu'),
            array('name' => '德国(Deutsche Post)','code' => 'deutschepost'),
            array('name' => '苏宁订单','code' => 'suningorder'),
            array('name' => '宜送物流','code' => 'yiex'),
            array('name' => 'AOL澳通速递','code' => 'aolau'),
            array('name' => 'TRAKPAK','code' => 'trakpak'),
            array('name' => 'GTS快递','code' => 'gts'),
            array('name' => '通达兴物流','code' => 'tongdaxing'),
            array('name' => '中国香港(HongKong Post)英文','code' => 'hkposten'),
            array('name' => '骏丰国际速递','code' => 'junfengguoji'),
            array('name' => '俄罗斯邮政(Russian Post)','code' => 'pochta'),
            array('name' => '云达通','code' => 'ydglobe'),
            array('name' => 'EU-EXPRESS','code' => 'euexpress'),
            array('name' => '广州海关','code' => 'gzcustoms'),
            array('name' => '杭州海关','code' => 'hzcustoms'),
            array('name' => '南京海关','code' => 'njcustoms'),
            array('name' => '北京海关','code' => 'bjcustoms'),
            array('name' => '美西快递','code' => 'meixi'),
            array('name' => '一站通快递','code' => 'zgyzt'),
            array('name' => '易联通达','code' => 'el56'),
            array('name' => '驿扬国际速运','code' => 'iyoungspeed'),
            array('name' => '途鲜物流','code' => 'ibenben'),
            array('name' => '豌豆物流','code' => 'wandougongzhu'),
            array('name' => '哥士传奇速递','code' => 'gscq365'),
            array('name' => '心怡物流','code' => 'alog'),
            array('name' => 'ME物流','code' => 'macroexpressco'),
            array('name' => '疯狂快递','code' => 'crazyexpress'),
            array('name' => '韩国邮政韩文','code' => 'koreapostkr'),
            array('name' => '全速物流','code' => 'quansu'),
            array('name' => '新杰物流','code' => 'sunjex'),
            array('name' => '鲁通快运','code' => 'lutong'),
            array('name' => '安的快递','code' => 'gda'),
            array('name' => '美国申通','code' => 'stoexpress'),
            array('name' => '法国小包（colissimo）','code' => 'colissimo'),
            array('name' => '泛捷国际速递','code' => 'epanex'),
            array('name' => '中远e环球','code' => 'cosco'),
            array('name' => '顺达快递','code' => 'sundarexpress'),
            array('name' => '捷记方舟','code' => 'ajexpress'),
            array('name' => '方舟速递','code' => 'arkexpress'),
            array('name' => '明大快递','code' => 'adaexpress'),
            array('name' => '长江国际速递','code' => 'changjiang'),
            array('name' => 'PCA Express','code' => 'pcaexpress'),
            array('name' => '洋包裹','code' => 'yangbaoguo'),
            array('name' => '优联吉运','code' => 'uluckex'),
            array('name' => '德豪驿','code' => 'dehaoyi'),
            array('name' => '堡昕德速递','code' => 'bosind'),
            array('name' => '阿根廷(Correo Argentina)','code' => 'correoargentino'),
            array('name' => '秘鲁(SERPOST)','code' => 'peru'),
            array('name' => '哈萨克斯坦(Kazpost)','code' => 'kazpost'),
            array('name' => '广通速递','code' => 'gtongsudi'),
            array('name' => '东瀚物流','code' => 'donghanwl'),
            array('name' => 'rpx','code' => 'rpx'),
            array('name' => '黑猫雅玛多','code' => 'yamato'),
            array('name' => '华通快运','code' => 'htongexpress'),
            array('name' => '吉尔吉斯斯坦(Kyrgyz Post)','code' => 'kyrgyzpost'),
            array('name' => '拉脱维亚(Latvijas Pasts)','code' => 'latvia'),
            array('name' => '黎巴嫩(Liban Post)','code' => 'libanpost'),
            array('name' => '立陶宛（Lietuvos pa?tas）','code' => 'lithuania'),
            array('name' => '马尔代夫(Maldives Post)','code' => 'maldives'),
            array('name' => '马耳他（Malta Post）','code' => 'malta'),
            array('name' => '马其顿(Macedonian Post)','code' => 'macedonia'),
            array('name' => '新西兰（New Zealand Post）','code' => 'newzealand'),
            array('name' => '摩尔多瓦(Posta Moldovei)','code' => 'moldova'),
            array('name' => '塞尔维亚(PE Post of Serbia)','code' => 'serbia'),
            array('name' => '塞浦路斯(Cyprus Post)','code' => 'cypruspost'),
            array('name' => '突尼斯EMS(Rapid-Poste)','code' => 'tunisia'),
            array('name' => '乌兹别克斯坦(Post of Uzbekistan)','code' => 'uzbekistan'),
            array('name' => '新喀里多尼亚[法国](New Caledonia)','code' => 'caledonia'),
            array('name' => '叙利亚(Syrian Post)','code' => 'republic'),
            array('name' => '亚美尼亚(Haypost-Armenian Postal)','code' => 'haypost'),
            array('name' => '也门(Yemen Post)','code' => 'yemen'),
            array('name' => '印度(India Post)','code' => 'india'),
            array('name' => '英国(大包,EMS)','code' => 'england'),
            array('name' => '约旦(Jordan Post)','code' => 'jordan'),
            array('name' => '越南小包(Vietnam Posts)','code' => 'vietnam'),
            array('name' => '黑山(Po?ta Crne Gore)','code' => 'montenegro'),
            array('name' => '哥斯达黎加(Correos de Costa Rica)','code' => 'correos'),
            array('name' => 'EFS Post（平安快递）','code' => 'efs'),
            array('name' => 'TNT Post','code' => 'tntpostcn'),
            array('name' => '立白宝凯物流','code' => 'lbbk'),
            array('name' => '匈牙利（Magyar Posta）','code' => 'hungary'),
            array('name' => '中国澳门(Macau Post)','code' => 'macao'),
            array('name' => '西安喜来快递','code' => 'xilaikd'),
            array('name' => '韩润','code' => 'hanrun'),
            array('name' => '格陵兰[丹麦]（TELE Greenland A/S）','code' => 'greenland'),
            array('name' => '菲律宾（Philippine Postal）','code' => 'phlpost'),
            array('name' => '厄瓜多尔(Correos del Ecuador)','code' => 'ecuador'),
            array('name' => '冰岛(Iceland Post)','code' => 'iceland'),
            array('name' => '波兰小包(Poczta Polska)','code' => 'emonitoring'),
            array('name' => '阿尔巴尼亚(Posta shqipatre)','code' => 'albania'),
            array('name' => '埃及（Egypt Post）','code' => 'egypt'),
            array('name' => '爱沙尼亚(Eesti Post)','code' => 'omniva'),
            array('name' => '云豹国际货运','code' => 'leopard'),
            array('name' => '中外运空运','code' => 'sinoairinex'),
            array('name' => '上海昊宏国际货物','code' => 'hyk'),
            array('name' => '城晓国际快递','code' => 'ckeex'),
            array('name' => '中铁物流','code' => 'ztky'),
            array('name' => '出口易','code' => 'chukou1'),
            array('name' => '跨畅（直邮易）','code' => 'kuachangwuliu'),
            array('name' => 'WTD海外通','code' => 'wtdex'),
            array('name' => 'CHS中环国际快递','code' => 'chszhonghuanguoji'),
            array('name' => '汉邦国际速递','code' => 'handboy'),
            array('name' => '银河物流','code' => 'milkyway'),
            array('name' => '荷兰速递(Nederland Post)','code' => 'nederlandpost'),
            array('name' => '澳州顺风快递','code' => 'emms'),
            array('name' => '环东物流','code' => 'huandonglg'),
            array('name' => '中邮速递','code' => 'wondersyd'),
            array('name' => '布谷鸟速递','code' => 'cuckooexpess'),
            array('name' => '万庚国际速递','code' => 'vangenexpress'),
            array('name' => 'FedRoad 联邦转运','code' => 'fedroad'),
            array('name' => 'Landmark Global','code' => 'landmarkglobal'),
            array('name' => '佳成快递','code' => 'jiacheng'),
            array('name' => '诺尔国际物流','code' => 'nuoer'),
            array('name' => '加运美速递','code' => 'jym56'),
            array('name' => '新时速物流','code' => 'csxss'),
            array('name' => '中宇天地','code' => 'zytdscm'),
            array('name' => '翔腾物流','code' => 'xiangteng'),
            array('name' => '恒瑞物流','code' => 'hengrui56'),
            array('name' => '中国翼','code' => 'cnws'),
            array('name' => '邦工快运','code' => 'bgky100'),
            array('name' => '上海无疆for买卖宝','code' => 'shanghaiwujiangmmb'),
            array('name' => '新加坡小包(Singapore Post)','code' => 'singpost'),
            array('name' => '中俄速通（淼信）','code' => 'mxe56'),
            array('name' => '海派通','code' => 'hipito'),
            array('name' => '源安达','code' => 'yuananda'),
            array('name' => '赛澳递for买卖宝','code' => 'saiaodimmb'),
            array('name' => 'ECMS Express','code' => 'ecmsglobal'),
            array('name' => '英脉物流','code' => 'gml'),
            array('name' => '佳家通货运','code' => 'jiajiatong56'),
            array('name' => '吉日优派','code' => 'jrypex'),
            array('name' => '西安胜峰','code' => 'xaetc'),
            array('name' => 'logen路坚','code' => 'ilogen'),
            array('name' => 'amazon-国际订单','code' => 'amusorder'),
            array('name' => 'CJ物流','code' => 'doortodoor'),
            array('name' => '转运四方','code' => 'zhuanyunsifang'),
            array('name' => '成都东骏物流','code' => 'dongjun'),
            array('name' => '日本?便','code' => 'japanpost'),
            array('name' => '猴急送','code' => 'hjs'),
            array('name' => '全信通快递','code' => 'quanxintong'),
            array('name' => '信天捷快递','code' => 'xintianjie'),
            array('name' => '泰国138国际物流','code' => 'sd138'),
            array('name' => '荷兰包裹(PostNL International Parcels)','code' => 'postnlpacle'),
            array('name' => '乐天速递','code' => 'ltexp'),
            array('name' => '智通物流','code' => 'ztong'),
            array('name' => '全速通','code' => 'quansutong'),
            array('name' => '中技物流','code' => 'zhongjiwuliu'),
            array('name' => '九曳供应链','code' => 'jiuyescm'),
            array('name' => '当当','code' => 'dangdang'),
            array('name' => '美龙快递','code' => 'mjexp'),
            array('name' => '唯品会(vip)','code' => 'vipshop'),
            array('name' => '1号店','code' => 'yhdshop'),
            array('name' => '皇家物流','code' => 'pfcexpress'),
            array('name' => '百千诚物流','code' => 'bqcwl'),
            array('name' => '法国(La Poste)','code' => 'csuivi'),
            array('name' => 'DHL-全球件','code' => 'dhlen'),
            array('name' => '运通中港','code' => 'yuntongkuaidi'),
            array('name' => '苏宁物流','code' => 'suning'),
            array('name' => '荷兰Sky Post','code' => 'skypost'),
            array('name' => '瑞达国际速递','code' => 'ruidaex'),
            array('name' => '丰程物流','code' => 'sccod'),
            array('name' => '德中快递','code' => 'decnlh'),
            array('name' => '全时速运','code' => 'runhengfeng'),
            array('name' => '云邮跨境快递','code' => 'hkems'),
            array('name' => '亚风速递','code' => 'yafengsudi'),
            array('name' => '快淘快递','code' => 'kuaitao'),
            array('name' => '鑫通宝物流','code' => 'xtb'),
            array('name' => 'USPS','code' => 'usps'),
            array('name' => '加拿大邮政','code' => 'canpostfr'),
            array('name' => '汇通天下物流','code' => 'httx56'),
            array('name' => '台湾（中华邮政）','code' => 'postserv'),
            array('name' => '好又快物流','code' => 'haoyoukuai'),
            array('name' => '永旺达快递','code' => 'yongwangda'),
            array('name' => '木春货运','code' => 'mchy'),
            array('name' => '程光快递','code' => 'flyway'),
            array('name' => '百事亨通','code' => 'bsht'),
            array('name' => '万家通快递','code' => 'timedg'),
            array('name' => '全之鑫物流','code' => 'qzx56'),
            array('name' => '美快国际物流','code' => 'meiquick'),
            array('name' => 'ILYANG','code' => 'ilyang'),
            array('name' => '先锋快递','code' => 'xianfeng'),
            array('name' => '亿顺航','code' => 'yishunhang'),
            array('name' => '尚橙物流','code' => 'shangcheng'),
            array('name' => 'OnTrac','code' => 'ontrac'),
            array('name' => 'TNT-全球件','code' => 'tnten'),
            array('name' => '顺丰-美国件','code' => 'shunfengen'),
            array('name' => '共速达','code' => 'gongsuda'),
            array('name' => '源伟丰','code' => 'yuanweifeng'),
            array('name' => '祥龙运通物流','code' => 'xianglongyuntong'),
            array('name' => '偌亚奥国际快递','code' => 'nuoyaao'),
            array('name' => '陪行物流','code' => 'peixingwuliu'),
            array('name' => 'CCES/国通快递','code' => 'cces'),
            array('name' => '彪记快递','code' => 'biaojikuaidi'),
            array('name' => '安信达','code' => 'anxindakuaixi'),
            array('name' => '配思货运','code' => 'peisihuoyunkuaidi'),
            array('name' => '大田物流','code' => 'datianwuliu'),
            array('name' => '邮政快递包裹','code' => 'youzhengguonei'),
            array('name' => '文捷航空','code' => 'wenjiesudi'),
            array('name' => 'BHT','code' => 'bht'),
            array('name' => '北青小红帽','code' => 'xiaohongmao'),
            array('name' => 'GSM','code' => 'gsm'),
            array('name' => '汇强快递','code' => 'huiqiangkuaidi'),
            array('name' => '昊盛物流','code' => 'haoshengwuliu'),
            array('name' => '联邦快递-英文','code' => 'lianbangkuaidien'),
            array('name' => '伍圆速递','code' => 'wuyuansudi'),
            array('name' => '南京100','code' => 'nanjing'),
            array('name' => '全通快运','code' => 'quantwl'),
            array('name' => '宅急便','code' => 'zhaijibian'),
            array('name' => '加拿大(Canada Post)','code' => 'canpost'),
            array('name' => 'COE','code' => 'coe'),
            array('name' => '百通物流','code' => 'buytong'),
            array('name' => '友家速递','code' => 'youjia'),
            array('name' => '新元快递','code' => 'xingyuankuaidi'),
            array('name' => '中澳速递','code' => 'cnausu'),
            array('name' => '联合快递','code' => 'gslhkd'),
            array('name' => '河南次晨达','code' => 'ccd'),
            array('name' => '奔腾物流','code' => 'benteng'),
            array('name' => '今枫国际快运','code' => 'mapleexpress'),
            array('name' => '中运全速','code' => 'topspeedex'),
            array('name' => '中欧快运','code' => 'otobv'),
            array('name' => '宜家行','code' => 'yjxlm'),
            array('name' => '金马甲','code' => 'jmjss'),
            array('name' => '一号仓','code' => 'onehcang'),
            array('name' => '论道国际物流','code' => 'lundao'),
            array('name' => '顺通快递','code' => 'stkd'),
            array('name' => 'globaltracktrace','code' => 'globaltracktrace'),
            array('name' => '德方物流','code' => 'ahdf'),
            array('name' => '速递中国','code' => 'sendtochina'),
            array('name' => 'NLE','code' => 'nle'),
            array('name' => '亚欧专线','code' => 'nlebv'),
            array('name' => '信联通','code' => 'sinatone'),
            array('name' => '澳德物流','code' => 'auod'),
            array('name' => '微转运','code' => 'wzhaunyun'),
            array('name' => 'iExpress','code' => 'iexpress'),
            array('name' => '远成快运','code' => 'ycgky'),
            array('name' => '高考通知书','code' => 'emsluqu'),
            array('name' => '安鲜达','code' => 'exfresh'),
            array('name' => 'BCWELT','code' => 'bcwelt'),
            array('name' => '欧亚专线','code' => 'euasia'),
            array('name' => '乐递供应链','code' => 'ledii'),
            array('name' => '万通快递','code' => 'gswtkd'),
            array('name' => '特急送','code' => 'lntjs'),
            array('name' => '金大物流','code' => 'jindawuliu'),
            array('name' => '民航快递','code' => 'minghangkuaidi'),
            array('name' => '红马甲物流','code' => 'sxhongmajia'),
            array('name' => 'amazon-国内订单','code' => 'amcnorder'),
            array('name' => 'ABF','code' => 'abf'),
            array('name' => '小米','code' => 'xiaomi'),
            array('name' => '新元国际','code' => 'xynyc'),
            array('name' => '小C海淘','code' => 'xiaocex'),
            array('name' => '航空快递','code' => 'airgtc'),
            array('name' => '叮咚澳洲转运','code' => 'dindon'),
            array('name' => '环球通达','code' => 'hqtd'),
            array('name' => '新西兰中通','code' => 'nzzto'),
            array('name' => '良藤国际速递','code' => 'lmfex'),
            array('name' => '速品快递','code' => 'supinexpress'),
            array('name' => '海龟国际快递','code' => 'turtle'),
            array('name' => '韩国邮政','code' => 'koreapostcn'),
            array('name' => '韵丰物流','code' => 'yunfeng56'),
            array('name' => '易达通快递','code' => 'qexpress'),
            array('name' => '一运全成物流','code' => 'yyqc56'),
            array('name' => '泛远国际物流','code' => 'farlogistis'),
            array('name' => '达速物流','code' => 'dasu'),
            array('name' => '恒通快递','code' => 'lqht'),
            array('name' => '壹品速递','code' => 'ypsd'),
            array('name' => '鹰运国际速递','code' => 'vipexpress'),
            array('name' => '南方传媒物流','code' => 'ndwl'),
            array('name' => '速呈宅配','code' => 'sucheng'),
            array('name' => '云南滇驿物流','code' => 'dianyi'),
            array('name' => '四川星程快递','code' => 'scxingcheng'),
            array('name' => '运通中港快递','code' => 'ytkd'),
            array('name' => 'Gati-英文','code' => 'gatien'),
            array('name' => 'jcex','code' => 'jcex'),
            array('name' => '凯信达','code' => 'kxda'),
            array('name' => '安达信','code' => 'advancing'),
            array('name' => '亿翔','code' => 'yxexpress'),
            array('name' => '加运美','code' => 'jiayunmeiwuliu'),
            array('name' => '赛澳递','code' => 'saiaodi'),
            array('name' => '康力物流','code' => 'kangliwuliu'),
            array('name' => '鑫飞鸿','code' => 'xinhongyukuaidi'),
            array('name' => '全一快递','code' => 'quanyikuaidi'),
            array('name' => '华企快运','code' => 'huaqikuaiyun'),
            array('name' => '青岛安捷快递','code' => 'anjiekuaidi'),
            array('name' => '递四方','code' => 'disifang'),
            array('name' => '三态速递','code' => 'santaisudi'),
            array('name' => '成都立即送','code' => 'lijisong'),
            array('name' => '河北建华','code' => 'hebeijianhua'),
            array('name' => '风行天下','code' => 'fengxingtianxia'),
            array('name' => '一统飞鸿','code' => 'yitongfeihong'),
            array('name' => '海外环球','code' => 'haiwaihuanqiu'),
            array('name' => 'DHL-中国件','code' => 'dhl'),
            array('name' => '西安城联速递','code' => 'xianchengliansudi'),
            array('name' => '一柒国际物流','code' => 'yiqiguojiwuliu'),
            array('name' => '广东通路','code' => 'guangdongtonglu'),
            array('name' => '中国香港骏辉物流','code' => 'chunfai'),
            array('name' => '三三国际物流','code' => 'zenzen'),
            array('name' => '比利时国际(Bpost international)','code' => 'bpostinter'),
            array('name' => '海红for买卖宝','code' => 'haihongmmb'),
            array('name' => 'FedEx-英国件（FedEx UK)','code' => 'fedexuk'),
            array('name' => 'FedEx-英国件','code' => 'fedexukcn'),
            array('name' => '叮咚快递','code' => 'dingdong'),
            array('name' => 'MRW','code' => 'mrw'),
            array('name' => 'Chronopost Portugal','code' => 'chronopostport'),
            array('name' => '西班牙(Correos de Espa?a)','code' => 'correosdees'),
            array('name' => '丹麦(Post Denmark)','code' => 'postdanmarken'),
            array('name' => 'Purolator','code' => 'purolator'),
            array('name' => '法国大包、EMS-法文（Chronopost France）','code' => 'chronopostfra'),
            array('name' => 'Selektvracht','code' => 'selektvracht'),
            array('name' => '比利时(Belgium Post)','code' => 'belgiumpost'),
            array('name' => '晟邦物流','code' => 'nanjingshengbang'),
            array('name' => 'UPS Mail Innovations','code' => 'upsmailinno'),
            array('name' => '挪威（Posten Norge）','code' => 'postennorge'),
            array('name' => '瑞士(Swiss Post)','code' => 'swisspost'),
            array('name' => '英国邮政小包','code' => 'royalmailcn'),
            array('name' => '英国小包（Royal Mail）','code' => 'royalmail'),
            array('name' => 'DHL Benelux','code' => 'dhlbenelux'),
            array('name' => 'DHL-荷兰（DHL Netherlands）','code' => 'dhlnetherlands'),
            array('name' => 'OPEK','code' => 'opek'),
            array('name' => 'Italy SDA','code' => 'italysad'),
            array('name' => 'Fastway Ireland','code' => 'fastway'),
            array('name' => 'DHL-波兰（DHL Poland）','code' => 'dhlpoland'),
            array('name' => 'DPD','code' => 'dpd'),
            array('name' => '速通物流','code' => 'sutongwuliu'),
            array('name' => '荷兰邮政-中文(PostNL international registered mail)','code' => 'postnlcn'),
            array('name' => '荷兰邮政(PostNL international registered mail)','code' => 'postnl'),
            array('name' => '乌克兰EMS(EMS Ukraine)','code' => 'emsukraine'),
            array('name' => '乌克兰邮政包裹','code' => 'ukrpostcn'),
            array('name' => '英国大包、EMS（Parcel Force）','code' => 'parcelforce'),
            array('name' => 'YODEL','code' => 'yodel'),
            array('name' => 'UBI Australia','code' => 'gotoubi'),
            array('name' => '红马速递','code' => 'nedahm'),
            array('name' => '云南诚中物流','code' => 'czwlyn'),
            array('name' => '万博快递','code' => 'wanboex'),
            array('name' => '腾达速递','code' => 'nntengda'),
            array('name' => '郑州速捷','code' => 'sujievip'),
            array('name' => '中睿速递','code' => 'zhongruisudi'),
            array('name' => '中天万运','code' => 'zhongtianwanyun'),
            array('name' => '新蛋奥硕','code' => 'neweggozzo'),
            array('name' => '七天连锁','code' => 'sevendays'),
            array('name' => 'UPS-全球件','code' => 'upsen'),
            array('name' => '跨越速运','code' => 'kuayue'),
            array('name' => '全际通','code' => 'quanjitong'),
            array('name' => 'UPS','code' => 'ups'),
            array('name' => '一邦速递','code' => 'yibangwuliu'),
            array('name' => '上海快通','code' => 'shanghaikuaitong'),
            array('name' => '品速心达快递','code' => 'pinsuxinda'),
            array('name' => 'PostNord(Posten AB)','code' => 'postenab'),
            array('name' => '城际速递','code' => 'chengjisudi'),
            array('name' => '户通物流','code' => 'hutongwuliu'),
            array('name' => '飞康达','code' => 'feikangda'),
            array('name' => '星晨急便','code' => 'xingchengjibian'),
            array('name' => '全日通','code' => 'quanritongkuaidi'),
            array('name' => '凤凰快递','code' => 'fenghuangkuaidi'),
            array('name' => '广东邮政','code' => 'guangdongyouzhengwuliu'),
            array('name' => '长宇物流','code' => 'changyuwuliu'),
            array('name' => '万家物流','code' => 'wanjiawuliu'),
            array('name' => 'EMS-国际件-英文','code' => 'emsinten'),
            array('name' => '飞远配送','code' => 'feiyuanvipshop'),
            array('name' => '国美','code' => 'gome'),
            array('name' => '能达速递','code' => 'ganzhongnengda'),
            array('name' => '急先达','code' => 'jixianda'),
            array('name' => '凡宇快递','code' => 'fanyukuaidi'),
            array('name' => '希优特','code' => 'xiyoutekuaidi'),
            array('name' => '中通（带电话）','code' => 'zhongtongphone'),
            array('name' => '蓝镖快递','code' => 'lanbiaokuaidi'),
            array('name' => '佳吉快运','code' => 'jiajiwuliu'),
            array('name' => '宏品物流','code' => 'hongpinwuliu'),
            array('name' => 'GLS','code' => 'gls'),
            array('name' => '原飞航','code' => 'yuanfeihangwuliu'),
            array('name' => '海红网送','code' => 'haihongwangsong'),
            array('name' => 'TNT','code' => 'tnt'),
            array('name' => '元智捷诚','code' => 'yuanzhijiecheng'),
            array('name' => '国际包裹','code' => 'youzhengguoji'),
            array('name' => '城市100','code' => 'city100'),
            array('name' => 'DPEX','code' => 'dpex'),
            array('name' => '芝麻开门','code' => 'zhimakaimen'),
            array('name' => 'EMS-国际件','code' => 'emsguoji'),
            array('name' => '晋越快递','code' => 'jinyuekuaidi'),
            array('name' => '乐捷递','code' => 'lejiedi'),
            array('name' => '飞力士物流','code' => 'flysman'),
            array('name' => '百腾物流','code' => 'baitengwuliu'),
            array('name' => '品骏快递','code' => 'pjbest'),
            array('name' => '瓦努阿图(Vanuatu Post)','code' => 'vanuatu'),
            array('name' => '巴巴多斯(Barbados Post)','code' => 'barbados'),
            array('name' => '萨摩亚(Samoa Post)','code' => 'samoa'),
            array('name' => '斐济(Fiji Post)','code' => 'fiji'),
            array('name' => '英超物流','code' => 'yingchao'),
            array('name' => 'TNY物流','code' => 'tny'),
            array('name' => '美通','code' => 'valueway'),
            array('name' => '新速航','code' => 'sunspeedy'),
            array('name' => '速方(Sufast)','code' => 'bphchina'),
            array('name' => '华航快递','code' => 'hzpl'),
            array('name' => 'Gati-KWE','code' => 'gatikwe'),
            array('name' => 'Red Express','code' => 'redexpress'),
            array('name' => 'Toll Priority(Toll Online)','code' => 'tollpriority'),
            array('name' => 'Estafeta','code' => 'estafeta'),
            array('name' => '港快速递','code' => 'gdkd'),
            array('name' => '墨西哥（Correos de Mexico）','code' => 'mexico'),
            array('name' => '罗马尼亚（Posta Romanian）','code' => 'romanian'),
            array('name' => 'DPD Poland','code' => 'dpdpoland'),
            array('name' => '阿联酋(Emirates Post)','code' => 'emirates'),
            array('name' => '新顺丰（NSF）','code' => 'nsf'),
            array('name' => '巴基斯坦(Pakistan Post)','code' => 'pakistan'),
            array('name' => 'Asendia USA','code' => 'asendiausa'),
            array('name' => '法国大包、EMS-英文(Chronopost France)','code' => 'chronopostfren'),
            array('name' => '意大利(Poste Italiane)','code' => 'italiane'),
            array('name' => '世运快递','code' => 'shiyunkuaidi'),
            array('name' => '新干线快递','code' => 'anlexpress'),
            array('name' => '飞洋快递','code' => 'shipgce'),
            array('name' => 'Xlobo贝海国际','code' => 'xlobo'),
            array('name' => '黄马甲','code' => 'huangmajia'),
            array('name' => 'Toll','code' => 'dpexen'),
            array('name' => '如风达','code' => 'rufengda'),
            array('name' => 'EC-Firstclass','code' => 'ecfirstclass'),
            array('name' => 'DTDC India','code' => 'dtdcindia'),
            array('name' => 'Safexpress','code' => 'safexpress'),
            array('name' => '泰国（Thailand Thai Post）','code' => 'thailand'),
            array('name' => 'SkyNet Malaysia','code' => 'skynetmalaysia'),
            array('name' => 'TNT Australia','code' => 'tntau'),
            array('name' => '马来西亚小包（Malaysia Post(Registered)）','code' => 'malaysiapost'),
            array('name' => '马来西亚大包、EMS（Malaysia Post(parcel,EMS)）','code' => 'malaysiaems'),
            array('name' => '沙特阿拉伯(Saudi Post)','code' => 'saudipost'),
            array('name' => '南非（South African Post Office）','code' => 'southafrican'),
            array('name' => 'Mexico Senda Express','code' => 'mexicodenda'),
            array('name' => 'MyHermes','code' => 'myhermes'),
            array('name' => 'DPD Germany','code' => 'dpdgermany'),
            array('name' => 'Nova Poshta','code' => 'novaposhta'),
            array('name' => 'Estes','code' => 'estes'),
            array('name' => 'TNT UK','code' => 'tntuk'),
            array('name' => 'Deltec Courier','code' => 'deltec'),
            array('name' => 'UPS Freight','code' => 'upsfreight'),
            array('name' => 'TNT Italy','code' => 'tntitaly'),
            array('name' => 'Mexico Multipack','code' => 'multipack'),
            array('name' => '葡萄牙（Portugal CTT）','code' => 'portugalctt'),
            array('name' => 'Interlink Express','code' => 'interlink'),
            array('name' => 'DPD UK','code' => 'dpduk'),
            array('name' => '乌克兰EMS-中文(EMS Ukraine)','code' => 'emsukrainecn'),
            array('name' => '乌克兰小包、大包(UkrPost)','code' => 'ukrpost'),
            array('name' => 'TCI XPS','code' => 'tcixps'),
            array('name' => '高铁速递','code' => 'hre'),
            array('name' => '新加坡EMS、大包(Singapore Speedpost)','code' => 'speedpost'),
            array('name' => 'LaserShip','code' => 'lasership'),
            array('name' => '英国邮政大包EMS','code' => 'parcelforcecn'),
            array('name' => '同舟行物流','code' => 'chinatzx'),
            array('name' => '秦邦快运','code' => 'qbexpress'),
            array('name' => 'skynet','code' => 'skynet'),
            array('name' => '忠信达','code' => 'zhongxinda'),
            array('name' => '门对门','code' => 'menduimen'),
            array('name' => '微特派','code' => 'weitepai'),
            array('name' => '海盟速递','code' => 'haimengsudi'),
            array('name' => '圣安物流','code' => 'shenganwuliu'),
            array('name' => '联邦快递','code' => 'lianbangkuaidi'),
            array('name' => '飞快达','code' => 'feikuaida'),
            array('name' => '天地华宇','code' => 'tiandihuayu'),
            array('name' => '煜嘉物流','code' => 'yujiawuliu'),
            array('name' => '郑州建华','code' => 'zhengzhoujianhua'),
            array('name' => '大洋物流','code' => 'dayangwuliu'),
            array('name' => '递达速运','code' => 'didasuyun'),
            array('name' => '易通达','code' => 'yitongda'),
            array('name' => '邮必佳','code' => 'youbijia'),
            array('name' => 'EMS-英文','code' => 'emsen'),
            array('name' => '闽盛快递','code' => 'minshengkuaidi'),
            array('name' => '佳惠尔','code' => 'syjiahuier'),
            array('name' => 'KCS','code' => 'kcs'),
            array('name' => 'ADP国际快递','code' => 'adp'),
            array('name' => '?达国际快递','code' => 'fardarww'),
            array('name' => '?达国际快递-英文','code' => 'fandaguoji'),
            array('name' => '林道国际快递','code' => 'shlindao'),
            array('name' => '中外运速递-中文','code' => 'sinoex'),
            array('name' => '中外运速递','code' => 'zhongwaiyun'),
            array('name' => '深圳德创物流','code' => 'dechuangwuliu'),
            array('name' => '林道国际快递-英文','code' => 'ldxpres'),
            array('name' => '中国香港(HongKong Post)','code' => 'hkpost'),
            array('name' => '邦送物流','code' => 'bangsongwuliu'),
            array('name' => '华赫物流','code' => 'nmhuahe'),
            array('name' => '顺捷丰达','code' => 'shunjiefengda'),
            array('name' => '天马迅达','code' => 'tianma'),
            array('name' => '恒宇运通','code' => 'hyytes'),
            array('name' => '考拉国际速递','code' => 'kaolaexpress'),
            array('name' => 'BlueDart','code' => 'bluedart'),
            array('name' => '日日顺快线','code' => 'rrskx'),
            array('name' => '运东西','code' => 'yundx'),
            array('name' => '黑狗物流','code' => 'higo'),
            array('name' => '鹏远国际速递','code' => 'pengyuanexpress'),
            array('name' => '安捷物流','code' => 'anjie88'),
            array('name' => '骏达快递','code' => 'jdexpressusa'),
            array('name' => 'C&C国际速递','code' => 'cncexp'),
            array('name' => '北京EMS','code' => 'bjemstckj'),
            array('name' => 'airpak expresss','code' => 'airpak'),
            array('name' => '荷兰邮政-中国件','code' => 'postnlchina'),
            array('name' => '大达物流','code' => 'idada'),
            array('name' => '益递物流','code' => 'edlogistics'),
            array('name' => '中外运','code' => 'esinotrans'),
            array('name' => '速派快递(FastGo)','code' => 'fastgo'),
            array('name' => '易客满','code' => 'ecmscn'),
            array('name' => '美国云达','code' => 'yundaexus'),
            array('name' => 'Toll','code' => 'toll'),
            array('name' => '深圳DPEX','code' => 'szdpex'),
            array('name' => '俄顺达','code' => 'eshunda'),
            array('name' => '广东速腾物流','code' => 'suteng'),
            array('name' => '新鹏快递','code' => 'gdxp'),
            array('name' => '平安达腾飞','code' => 'pingandatengfei'),
            array('name' => '穗佳物流','code' => 'suijiawuliu'),
            array('name' => '传喜物流','code' => 'chuanxiwuliu'),
            array('name' => '捷特快递','code' => 'jietekuaidi'),
            array('name' => '隆浪快递','code' => 'longlangkuaidi'),
            array('name' => '佳吉快递','code' => 'jiajikuaidi'),
            array('name' => '飞狐快递','code' => 'feihukuaidi'),
            array('name' => '潇湘晨报','code' => 'xiaoxiangchenbao'),
            array('name' => '巴伦支','code' => 'balunzhi'),
            array('name' => '安能物流','code' => 'annengwuliu'),
            array('name' => '亿领速运','code' => 'yilingsuyun'),
            array('name' => '店通快递','code' => 'diantongkuaidi'),
            array('name' => 'OCA Argentina','code' => 'ocaargen'),
            array('name' => '尼日利亚(Nigerian Postal)','code' => 'nigerianpost'),
            array('name' => '智利(Correos Chile)','code' => 'chile'),
            array('name' => '以色列(Israel Post)','code' => 'israelpost'),
            array('name' => '奥地利(Austrian Post)','code' => 'austria'),
            array('name' => '乌克兰小包、大包(UkrPoshta)','code' => 'ukraine'),
            array('name' => '乌干达(Posta Uganda)','code' => 'uganda'),
            array('name' => '阿塞拜疆EMS(EMS AzerExpressPost)','code' => 'azerbaijan'),
            array('name' => '芬兰(Itella Posti Oy)','code' => 'finland'),
            array('name' => '斯洛伐克(Slovenská Posta)','code' => 'slovak'),
            array('name' => '阿鲁巴[荷兰]（Post Aruba）','code' => 'aruba'),
            array('name' => '爱尔兰(An Post)','code' => 'ireland'),
            array('name' => '印度尼西亚EMS(Pos Indonesia-EMS)','code' => 'indonesia'),
            array('name' => '易优包裹','code' => 'eupackage'),
            array('name' => '威时沛运货运','code' => 'wtdchina'),
            array('name' => '行必达','code' => 'speeda'),
            array('name' => '中通国际','code' => 'zhongtongguoji'),
            array('name' => '千顺快递','code' => 'qskdyxgs'),
            array('name' => '西邮寄','code' => 'xipost'),
            array('name' => '顺捷达','code' => 'shunjieda'),
            array('name' => 'CE易欧通国际速递','code' => 'cloudexpress'),
            array('name' => '和丰同城','code' => 'hfwuxi'),
            array('name' => '天联快运','code' => 'tlky'),
            array('name' => '优速物流','code' => 'youshuwuliu'),
            array('name' => '埃塞俄比亚(Ethiopian postal)','code' => 'ethiopia'),
            array('name' => '卢森堡(Luxembourg Post)','code' => 'luxembourg'),
            array('name' => '毛里求斯(Mauritius Post)','code' => 'mauritius'),
            array('name' => '文莱(Brunei Postal)','code' => 'brunei'),
            array('name' => 'Quantium','code' => 'quantium'),
            array('name' => '中铁快运','code' => 'zhongtiewuliu'),
            array('name' => '宇鑫物流','code' => 'yuxinwuliu'),
            array('name' => '巴林(Bahrain Post)','code' => 'bahrain'),
            array('name' => '纳米比亚(NamPost)','code' => 'namibia'),
            array('name' => '卢旺达(Rwanda i-posita)','code' => 'rwanda'),
            array('name' => '莱索托(Lesotho Post)','code' => 'lesotho'),
            array('name' => '肯尼亚(POSTA KENYA)','code' => 'kenya'),
            array('name' => '喀麦隆(CAMPOST)','code' => 'cameroon'),
            array('name' => '伯利兹(Belize Postal)','code' => 'belize'),
            array('name' => '巴拉圭(Correo Paraguayo)','code' => 'paraguay'),
            array('name' => '波黑(JP BH Posta)','code' => 'bohei'),
            array('name' => '玻利维亚','code' => 'bolivia'),
            array('name' => '柬埔寨(Cambodia Post)','code' => 'cambodia'),
            array('name' => '兰州伙伴物流','code' => 'huoban'),
            array('name' => '天纵物流','code' => 'tianzong'),
            array('name' => '坦桑尼亚(Tanzania Posts)','code' => 'tanzania'),
            array('name' => '阿曼(Oman Post)','code' => 'oman'),
            array('name' => '直布罗陀[英国]( Royal Gibraltar Post)','code' => 'gibraltar'),
            array('name' => '展勤快递','code' => 'byht'),
            array('name' => '越南EMS(VNPost Express)','code' => 'vnpost'),
            array('name' => '安迅物流','code' => 'anxl'),
            array('name' => '达方物流','code' => 'dfpost'),
            array('name' => '十方通物流','code' => 'sfift'),
            array('name' => '飞鹰物流','code' => 'hnfy'),
            array('name' => 'UPS i-parcel','code' => 'iparcel'),
            array('name' => '鑫锐达','code' => 'bjxsrd'),
            array('name' => '孟加拉国(EMS)','code' => 'bangladesh'),
            array('name' => '快捷速递','code' => 'kuaijiesudi'),
            array('name' => '日本（Japan Post）','code' => 'japanposten'),
            array('name' => '众辉达物流','code' => 'zhdwl'),
            array('name' => '秦远物流','code' => 'qinyuan'),
            array('name' => '澳邮中国快运','code' => 'auexpress'),
            array('name' => '日益通速递','code' => 'rytsd'),
            array('name' => '航宇快递','code' => 'hangyu'),
            array('name' => '急顺通','code' => 'pzhjst'),
            array('name' => '优速通达','code' => 'yousutongda'),
            array('name' => '飞邦快递','code' => 'fbkd'),
            array('name' => '华达快运','code' => 'huada'),
            array('name' => 'FOX国际快递','code' => 'fox'),
            array('name' => '佳怡物流','code' => 'jiayiwuliu'),
            array('name' => '鹏程快递','code' => 'pengcheng'),
            array('name' => '冠庭国际物流','code' => 'guanting'),
            array('name' => '美国快递','code' => 'meiguokuaidi'),
            array('name' => '通和天下','code' => 'tonghetianxia'),
            array('name' => '音素快运','code' => 'yinsu'),
            array('name' => '创一快递','code' => 'chuangyi'),
            array('name' => '重庆星程快递','code' => 'cqxingcheng'),
            array('name' => '贵州星程快递','code' => 'gzxingcheng'),
            array('name' => '河南全速通','code' => 'hnqst'),
            array('name' => '快速递','code' => 'ksudi'),
            array('name' => '北极星快运','code' => 'polarisexpress'),
            array('name' => '6LS EXPRESS','code' => 'lsexpress'),
            array('name' => 'ANTS EXPRESS','code' => 'qdants'),
            array('name' => 'S2C','code' => 's2c'),
            array('name' => 'Hi淘易快递','code' => 'hitaoe'),
            array('name' => 'CNAIR','code' => 'cnair'),
            array('name' => '易欧洲国际物流','code' => 'yiouzhou'),
            array('name' => '阳光快递','code' => 'shiningexpress'),
            array('name' => '北京丰越供应链','code' => 'beijingfengyue'),
            array('name' => '华中快递','code' => 'cpsair'),
            array('name' => '青旅物流','code' => 'zqlwl'),
            array('name' => '易航物流','code' => 'yihangmall'),
            array('name' => '城铁速递','code' => 'cex'),
            array('name' => '千里速递','code' => 'qianli'),
            array('name' => '急递','code' => 'jdpplus'),
            array('name' => '佳捷翔物流','code' => 'jjx888'),
            array('name' => '洋口岸','code' => 'ykouan'),
            array('name' => '考拉速递','code' => 'koalaexp'),
            array('name' => '天越物流','code' => 'surpassgo'),
            array('name' => '邮政标准快递','code' => 'youzhengbk'),
            array('name' => '运通快运','code' => 'ytky168'),
            array('name' => '卢森堡航空','code' => 'cargolux'),
            array('name' => '优优速递','code' => 'youyou'),
            array('name' => '全川物流','code' => 'quanchuan56'),
            array('name' => 'SYNSHIP快递','code' => 'synship'),
            array('name' => '仓鼠快递','code' => 'cangspeed'),
            array('name' => '递五方云仓','code' => 'di5pll'),
            array('name' => '卓志速运','code' => 'chinaicip'),
            array('name' => '闪电兔','code' => 'shandiantu'),
            array('name' => '新宁物流','code' => 'xinning'),
            array('name' => '春风物流','code' => 'spring56'),
            array('name' => '首达速运','code' => 'sdsy888'),
            array('name' => '丽狮物流','code' => 'lishi'),
            array('name' => '雅澳物流','code' => 'yourscm'),
            array('name' => '直德邮','code' => 'zdepost'),
            array('name' => '日昱物流','code' => 'riyuwuliu'),
            array('name' => 'Gati-中文','code' => 'gaticn'),
            array('name' => '派尔快递','code' => 'peex'),
            array('name' => '汇文','code' => 'huiwen'),
            array('name' => '东红物流','code' => 'donghong'),
            array('name' => '增益速递','code' => 'zengyisudi'),
            array('name' => '好运来','code' => 'hlyex'),
            array('name' => '城际快递','code' => 'chengji'),
            array('name' => '程光快递','code' => 'chengguangkuaidi'),
            array('name' => '天翼快递','code' => 'tykd'),
            array('name' => '京东订单','code' => 'jdorder'),
            array('name' => '蓝天快递','code' => 'lantiankuaidi'),
            array('name' => '永昌物流','code' => 'yongchangwuliu'),
            array('name' => '笨鸟海淘','code' => 'birdex'),
            array('name' => '一正达速运','code' => 'yizhengdasuyun'),
            array('name' => '德意思','code' => 'dabei'),
            array('name' => '佐川急便','code' => 'sagawa'),
            array('name' => '优配速运','code' => 'sdyoupei'),
            array('name' => '速必达','code' => 'subida'),
            array('name' => '景光物流','code' => 'jgwl'),
            array('name' => '御风速运','code' => 'yufeng'),
            array('name' => '至诚通达快递','code' => 'zhichengtongda'),
            array('name' => '特急便物流','code' => 'sucmj'),
            array('name' => '亚马逊中国','code' => 'yamaxunwuliu'),
            array('name' => '货运皇','code' => 'kingfreight'),
            array('name' => '锦程物流','code' => 'jinchengwuliu'),
            array('name' => '澳货通','code' => 'auex'),
            array('name' => '澳速物流','code' => 'aosu'),
            array('name' => '澳世速递','code' => 'aus'),
            array('name' => '环球速运','code' => 'huanqiu'),
            array('name' => '瑞丰速递','code' => 'rfsd'),
            array('name' => '美联快递','code' => 'letseml'),
            array('name' => 'CNPEX中邮快递','code' => 'cnpex'),
            array('name' => '鑫世锐达','code' => 'xsrd'),
            array('name' => '顺丰优选','code' => 'sfbest'),
            array('name' => '全峰快递','code' => 'quanfengkuaidi'),
            array('name' => '克罗地亚（Hrvatska Posta）','code' => 'hrvatska'),
            array('name' => '保加利亚（Bulgarian Posts）','code' => 'bulgarian'),
            array('name' => 'Portugal Seur','code' => 'portugalseur'),
            array('name' => 'International Seur','code' => 'seur'),
            array('name' => '久易快递','code' => 'jiuyicn'),
            array('name' => 'Direct Link','code' => 'directlink'),
            array('name' => '希腊EMS（ELTA Courier）','code' => 'eltahell'),
            array('name' => '捷克（?eská po?ta）','code' => 'ceskaposta'),
            array('name' => 'Siodemka','code' => 'siodemka'),
            array('name' => '爱尔兰(An Post)','code' => 'anposten'),
            array('name' => '渥途国际速运','code' => 'wotu'),
            array('name' => '一号线','code' => 'lineone'),
            array('name' => '四海快递','code' => 'sihaiet'),
            array('name' => '德坤物流','code' => 'dekuncn'),
            array('name' => '准实快运','code' => 'zsky123'),
            array('name' => '宏捷国际物流','code' => 'hongjie'),
            array('name' => '鸿讯物流','code' => 'hongxun'),
            array('name' => '卡邦配送','code' => 'ahkbps'),
            array('name' => '凡客配送（作废）','code' => 'vancl'),
            array('name' => '瑞士邮政','code' => 'swisspostcn'),
            array('name' => '辉联物流','code' => 'huilian'),
            array('name' => 'A2U速递','code' => 'a2u'),
            array('name' => 'UEQ快递','code' => 'ueq'),
            array('name' => '中加国际快递','code' => 'scic'),
            array('name' => '易达通','code' => 'yidatong'),
            array('name' => '宜送','code' => 'yisong'),
            array('name' => '全球快运','code' => 'abcglobal'),
            array('name' => '芒果速递','code' => 'mangguo'),
            array('name' => '金海淘','code' => 'goldhaitao'),
            array('name' => '极光转运','code' => 'jiguang'),
            array('name' => '富腾达国际货运','code' => 'ftd'),
            array('name' => 'DCS','code' => 'dcs'),
            array('name' => '捷网俄全通','code' => 'ruexp'),
            array('name' => '华通务达物流','code' => 'htwd'),
            array('name' => '申必达','code' => 'speedoex'),
            array('name' => '联运快递','code' => 'lianyun'),
            array('name' => '捷安达','code' => 'jieanda'),
            array('name' => 'SHL畅灵国际物流','code' => 'shlexp'),
            array('name' => 'EWE全球快递','code' => 'ewe'),
            array('name' => '顺邦国际物流','code' => 'shunbang'),
            array('name' => '成达国际速递','code' => 'chengda'),
            array('name' => '启辰国际速递','code' => 'qichen'),
            array('name' => '合众速递(UCS）','code' => 'ucs'),
            array('name' => '阿富汗(Afghan Post)','code' => 'afghan'),
            array('name' => '白俄罗斯(Belpochta)','code' => 'belpost'),
            array('name' => '冠捷物流','code' => 'gjwl'),
            array('name' => '钏博物流','code' => 'cbo56'),
            array('name' => '西翼物流','code' => 'westwing'),
            array('name' => '优邦速运','code' => 'ubonex'),
            array('name' => '首通快运','code' => 'staky'),
            array('name' => '马珂博逻','code' => 'cnmcpl'),
            array('name' => '小熊物流','code' => 'littlebearbear'),
            array('name' => '' . "\0" . 'h玛速运','code' => 'yue777'),
            array('name' => '上海航瑞货运','code' => 'hangrui'),
            array('name' => '星云速递','code' => 'nebuex'),
            array('name' => '环创物流','code' => 'ghl'),
            array('name' => '林安物流','code' => 'lasy56'),
            array('name' => '笨鸟国际','code' => 'benniao'),
            array('name' => '全速快递','code' => 'fsexp'),
            array('name' => '法翔速运','code' => 'ftlexpress'),
            array('name' => '易转运','code' => 'ezhuanyuan'),
            array('name' => 'Superb Grace','code' => 'superb'),
            array('name' => '蓝天国际快递','code' => 'ltx'),
            array('name' => '圣飞捷快递','code' => 'sfjhd'),
            array('name' => '淘韩国际快递','code' => 'krtao'),
            array('name' => '容智快运','code' => 'gdrz58'),
            array('name' => '锦程快递','code' => 'hrex'),
            array('name' => '顺时达物流','code' => 'hnssd56'),
            array('name' => '骏绅物流','code' => 'jsexpress'),
            array('name' => '德国雄鹰速递','code' => 'adlerlogi'),
            array('name' => '远为快递','code' => 'ywexpress'),
            array('name' => '嗖一下同城快递','code' => 'sofast56'),
            array('name' => '开心快递','code' => 'happylink'),
            array('name' => '五六快运','code' => 'wuliuky'),
            array('name' => '卓烨快递','code' => 'hrbzykd'),
            array('name' => 'ZTE中兴物流','code' => 'zteexpress'),
            array('name' => '尼尔快递','code' => 'nell'),
            array('name' => '高铁快运','code' => 'gaotieex'),
            array('name' => '万家康物流','code' => 'wjkwl'),
            array('name' => '国晶物流','code' => 'xdshipping'),
            array('name' => '德国云快递','code' => 'yunexpress'),
            array('name' => '宏递快运','code' => 'hd'),
            array('name' => '一起送','code' => 'yiqisong'),
            array('name' => '迈隆递运','code' => 'mailongdy'),
            array('name' => '新亚物流','code' => 'nalexpress'),
            array('name' => '艾瑞斯远','code' => 'ariesfar'),
            array('name' => '澳多多国际速递','code' => 'adodoxm'),
            array('name' => 'CNUP 中联邮','code' => 'cnup'),
            array('name' => 'UEX国际物流','code' => 'uex'),
            array('name' => 'Hermes','code' => 'hermes'),
            array('name' => 'PostElbe','code' => 'postelbe'),
            array('name' => '维普恩物流','code' => 'vps'),
            array('name' => '明辉物流','code' => 'zsmhwl'),
            array('name' => '联运通物流','code' => 'szuem'),
            array('name' => '龙象国际物流','code' => 'edragon'),
            array('name' => '永邦国际物流','code' => 'yongbangwuliu'),
            array('name' => '51跨境通','code' => 'wykjt'),
            array('name' => '速配欧翼','code' => 'superoz'),
            array('name' => '嘉里大荣物流','code' => 'kerrytj'),
            array('name' => '中国香港环球快运','code' => 'huanqiuabc'),
            array('name' => 'CL日中速运','code' => 'clsp'),
            array('name' => 'SQK国际速递','code' => 'chinasqk'),
            array('name' => '家家通快递','code' => 'newsway'),
            array('name' => '邮客全球速递','code' => 'yyox'),
            array('name' => '华瀚快递','code' => 'hhair56'),
            array('name' => '顺士达速运','code' => 'shunshid'),
            array('name' => '天翔东捷运','code' => 'djy56'),
            array('name' => '卓实快运','code' => 'zhuoshikuaiyun'),
            array('name' => '吉祥邮（澳洲）','code' => 'jixiangyouau'),
            array('name' => '蓝天快递','code' => 'blueskyexpress'),
            array('name' => '天天快物流','code' => 'guoeryue'),
            array('name' => '纵通速运','code' => 'ynztsy'),
            array('name' => '中通快运','code' => 'zhongtongkuaiyun'),
            array('name' => 'CNE','code' => 'cnexps'),
            array('name' => '希腊包裹（ELTA Hellenic Post）','code' => 'elta'),
            array('name' => '星速递','code' => 'starex'),
            array('name' => '土耳其','code' => 'ptt'),
            array('name' => '哥伦比亚(4-72 La Red Postal de Colombia)','code' => 'colombia'),
            array('name' => '加州猫速递','code' => 'jiazhoumao'),
            array('name' => '捷邦物流','code' => 'jieborne'),
            array('name' => '邮政国内','code' => 'yzguonei'),
            array('name' => 'Canpar','code' => 'canpar'),
            array('name' => '海硕高铁速递','code' => 'hsgtsd'),
            array('name' => '日日通国际','code' => 'rrthk'),
            array('name' => '天翼物流','code' => 'tywl99'),
            array('name' => '啪啪供应链','code' => 'papascm'),
            array('name' => '万达美','code' => 'wdm'),
            array('name' => '安得物流','code' => 'annto'),
            array('name' => '广东诚通物流','code' => 'gdct56'),
            array('name' => '安达速递','code' => 'adapost'),
            array('name' => '易达国际速递','code' => 'eta100'),
            array('name' => '西游寄','code' => 'xiyoug'),
            array('name' => '光线速递','code' => 'gxwl'),
            array('name' => '易邮国际','code' => 'euguoji'),
            array('name' => '深圳邮政','code' => 'szyouzheng'),
            array('name' => '粤中国际货运代理（上海）有限公司','code' => 'yuezhongsh'),
            array('name' => '城通物流','code' => 'chengtong'),
            array('name' => 'GE2D跨境物流','code' => 'ge2d'),
            array('name' => '败欧洲','code' => 'europe8'),
            array('name' => '?斯特','code' => 'bester'),
            array('name' => '蒙古国(Mongol Post)','code' => 'mongolpost'),
            array('name' => '乌拉圭（Correo Uruguayo）','code' => 'correo'),
            array('name' => '牙买加（Jamaica Post）','code' => 'jamaicapost'),
            array('name' => '格鲁吉亚(Georgian Pos）','code' => 'georgianpost'),
            array('name' => '美达快递','code' => 'meidaexpress'),
            array('name' => '驭丰速运','code' => 'yfsuyun'),
            array('name' => '无忧物流','code' => 'aliexpress'),
            array('name' => '邮鸽速运','code' => 'ugoexpress'),
            array('name' => '澳洲新干线快递','code' => 'expressplus'),
            array('name' => '标杆物流','code' => 'bmlchina'),
            array('name' => '长风物流','code' => 'longvast'),
            array('name' => '邮来速递','code' => 'youlai'),
            array('name' => '魔速达','code' => 'mosuda'),
            array('name' => '商桥物流','code' => 'shangqiao56'),
            array('name' => 'AUV国际快递','code' => 'auvexpress'),
            array('name' => 'Newgistics','code' => 'newgistics'),
            array('name' => 'FQ狂派速递','code' => 'freakyquick'),
            array('name' => '泽西岛','code' => 'jerseypost'),
            array('name' => '威盛快递','code' => 'wherexpess'),
            array('name' => '运通速运','code' => 'yuntong'),
            array('name' => '老挝(Lao Express)','code' => 'lao'),
            array('name' => '巴布亚新几内亚(PNG Post)','code' => 'postpng'),
            array('name' => 'EASY EXPRESS','code' => 'easyexpress'),
            array('name' => '壹米滴答','code' => 'yimidida'),
            array('name' => '飞云快递系统','code' => 'fyex'),
            array('name' => '跨跃国际','code' => 'kyue'),
            array('name' => 'EMS包裹','code' => 'emsbg'),
            array('name' => '珠峰速运','code' => 'zf365'),
            array('name' => '甘肃安的快递','code' => 'gansuandi'),
            array('name' => '一辉物流','code' => 'yatfai'),
            array('name' => 'e直运','code' => 'edtexpress'),
            array('name' => 'wish邮','code' => 'shpostwish'),
            array('name' => '顶世国际物流','code' => 'topshey'),
            array('name' => '龙枫国际快递','code' => 'lfexpress'),
            array('name' => '安能快递','code' => 'ane66'),
            array('name' => '圆通快运','code' => 'yuantongkuaiyun'),
            array('name' => '宝通快递','code' => 'baotongkd'),
            array('name' => '美国汉邦快递','code' => 'aplus100'),
            array('name' => '易普递','code' => 'sixroad'),
            array('name' => '速呈','code' => 'sczpds'),
            array('name' => '海淘物流','code' => 'ht22'),
            array('name' => '海米派物流','code' => 'haimibuy'),
            array('name' => '天翔快递','code' => 'tianxiang'),
            array('name' => '易境达国际物流','code' => 'uscbexpress'),
            array('name' => '大韩通运','code' => 'cjkoreaexpress'),
            array('name' => '澳世速递','code' => 'ausexpress'),
            array('name' => '未来明天快递','code' => 'weilaimingtian'),
            array('name' => '科捷物流','code' => 'kejie'),
            array('name' => '大道物流','code' => 'dadaoex'),
            array('name' => '全联速运','code' => 'guexp'),
            array('name' => '可可树美中速运','code' => 'excocotree'),
            array('name' => '邮邦国际','code' => 'youban'),
            array('name' => '西安运逸快递','code' => 'yyexp'),
            array('name' => 'Aplus物流','code' => 'aplusex'),
            array('name' => '锋鸟物流','code' => 'beebird'),
            array('name' => '青云物流','code' => 'bjqywl'),
            array('name' => '万邑通','code' => 'winit'),
            array('name' => '中翼国际物流','code' => 'chnexp'),
            array('name' => '亚洲顺物流','code' => 'yzswuliu'),
            array('name' => 'E跨通','code' => 'ecallturn'),
            array('name' => '递四方美国','code' => 'disifangus'),
            array('name' => '星空国际','code' => 'wlwex'),
            array('name' => '极地快递','code' => 'polarexpress'),
            array('name' => '到了港','code' => 'camekong'),
            array('name' => '斯里兰卡(Sri Lanka Post)','code' => 'slpost'),
            array('name' => '斯洛文尼亚(Slovenia Post)','code' => 'slovenia'),
            array('name' => '多米尼加（INPOSDOM ? Instituto Postal Dominicano）','code' => 'inposdom'),
            array('name' => '星运快递','code' => 'staryvr'),
            array('name' => '狮爱高铁物流','code' => 'sycawl'),
            array('name' => '爱拜物流','code' => 'ibuy8'),
            array('name' => '商海德物流','code' => 'shd56'),
            array('name' => '九宫物流','code' => 'jiugong'),
            array('name' => '缔惠盛合','code' => 'twkd56'),
            array('name' => '快服务','code' => 'kfwnet'),
            array('name' => 'dhl小包','code' => 'dhlecommerce'),
            array('name' => '宇佳物流','code' => 'yujiawl'),
            array('name' => '湘达物流','code' => 'xiangdawuliu'),
            array('name' => '远盾物流','code' => 'yuandun'),
            array('name' => '黑猫宅急便','code' => 'tcat'),
            array('name' => '韵达快运','code' => 'yundakuaiyun'),
            array('name' => '速派快递','code' => 'fastgoexpress'),
            array('name' => '中集冷云','code' => 'cccc58'),
            array('name' => '久久物流','code' => 'jiujiuwl'),
            array('name' => '德国八易转运','code' => 'deguo8elog'),
            array('name' => 'UTAO优到','code' => 'utaoscm'),
            array('name' => '乾坤物流','code' => 'yatexpress'),
            array('name' => '摩洛哥 ( Morocco Post )','code' => 'morocco'),
            array('name' => '尼泊尔（Nepal Postal Services）','code' => 'nepalpost'),
            array('name' => '伊朗（Iran Post）','code' => 'iran'),
            array('name' => '坦桑尼亚（Tanzania Posts Corporation）','code' => 'posta'),
            array('name' => '莫桑比克（Correios de Mo?ambique）','code' => 'correios'),
            array('name' => '聚中大','code' => 'juzhongda'),
            array('name' => '中邮电商','code' => 'chinapostcb'),
            array('name' => '鸿泰物流','code' => 'hnht56'),
            array('name' => '南非EMS','code' => 'emssouthafrica'),
            array('name' => '申通国际','code' => 'stosolution'),
            array('name' => '皮牙子快递','code' => 'bazirim'),
            array('name' => '联众国际','code' => 'epspost'),
            array('name' => '丰通快运','code' => 'ftky365'),
            array('name' => 'BorderGuru','code' => 'borderguru'),
            array('name' => '艾姆勒','code' => 'imlb2c'),
            array('name' => '中欧国际物流','code' => 'eucnrail'),
            array('name' => '递四方澳洲','code' => 'disifangau'),
            array('name' => '艺凡快递','code' => 'yifankd'),
            array('name' => '宏观国际快递','code' => 'gvpexpress'),
            array('name' => '博茨瓦纳','code' => 'botspost'),
            array('name' => '塞内加尔','code' => 'laposte'),
            array('name' => '卡塔尔（Qatar Post）','code' => 'qpost'),
            array('name' => '苏丹（Sudapost）','code' => 'sudapost'),
            array('name' => 'Sureline冠泰','code' => 'sureline'),
            array('name' => '海沧无忧','code' => 'hivewms'),
            array('name' => '安世通快递','code' => 'astexpress'),
            array('name' => '集先锋快递','code' => 'jxfex'),
            array('name' => '丰客物流','code' => 'fecobv'),
            array('name' => '同城快寄','code' => 'shpost'),
            array('name' => '海联快递','code' => 'hltop'),
            array('name' => '中联速递','code' => 'auvanda'),
            array('name' => '三象速递','code' => 'sxexpress'),
            array('name' => '神马快递','code' => 'shenma'),
            array('name' => '互联快运','code' => 'hlkytj'),
            array('name' => '温通物流','code' => 'wto56kj'),
            array('name' => '四海捷运','code' => 'sihiexpress'),
            array('name' => '苏通快运','code' => 'zjstky'),
            array('name' => '邦通国际','code' => 'comexpress'),
            array('name' => '劲通快递','code' => 'jintongkd'),
            array('name' => '凡仕特物流','code' => 'wlfast'),
            array('name' => '红背心','code' => 'hongbeixin'),
            array('name' => '居家通','code' => 'homexpress'),
            array('name' => '上大物流','code' => 'shangda'),
            array('name' => '中邮物流','code' => 'zhongyouwuliu'),
            array('name' => 'Fedex-国际件-中文','code' => 'fedexcn'),
            array('name' => '韩国（Korea Post）','code' => 'koreapost'),
            array('name' => '京广速递','code' => 'jinguangsudikuaijian'),
            array('name' => 'FedEx-国际件','code' => 'fedex'),
            array('name' => '日日顺物流','code' => 'rrs'),
            array('name' => '微店','code' => 'weidianorder'),
            array('name' => '当当','code' => 'dangdangorder'),
            array('name' => '国送快运','code' => 'guosong'),
            array('name' => '考拉订单','code' => 'kaolaorder'),
            array('name' => 'AAE-中国件','code' => 'aae'),
            array('name' => '四川快优达速递','code' => 'kuaiyouda'),
            array('name' => '百福东方','code' => 'baifudongfang'),
            array('name' => 'TST速运通','code' => 'tstexp'),
            array('name' => 'YUN TRACK','code' => 'yuntrack'),
            array('name' => '招金精炼','code' => 'zhaojin'),
            array('name' => '全程快递','code' => 'agopost'),
            array('name' => 'CDEK','code' => 'cdek'),
            array('name' => '签收快递','code' => 'signedexpress'),
            array('name' => '佰麒快递','code' => 'beckygo'),
            array('name' => '增速跨境','code' => 'zyzoom'),
            array('name' => 'Aramex','code' => 'aramex'),
            array('name' => '越中国际物流','code' => 'vctrans'),
            array('name' => '德国优拜物流','code' => 'ubuy'),
            array('name' => '德尚国际速递','code' => 'gslexpress'),
            array('name' => '德国 EUC POST','code' => 'eucpost'),
            array('name' => '泰国中通ZTO','code' => 'thaizto'),
            array('name' => '泰国中通CTO','code' => 'ctoexp'),
            array('name' => '顺丰-繁体','code' => 'shunfenghk'),
            array('name' => '嘉诚速达','code' => 'jcsuda'),
            array('name' => 'AFL','code' => 'afl'),
            array('name' => '众派速递','code' => 'zhpex'),
            array('name' => '海星桥快递','code' => 'haixingqiao'),
            array('name' => '蘑菇街','code' => 'mogujieorder'),
            array('name' => '嘉里大通','code' => 'jialidatong'),
            array('name' => '万象物流','code' => 'wanxiangwuliu'),
            array('name' => '澳大利亚(Australia Post)','code' => 'auspost'),
            array('name' => '国通快递','code' => 'guotongkuaidi'),
            array('name' => '全晨快递','code' => 'quanchenkuaidi'),
            array('name' => '飞豹快递','code' => 'feibaokuaidi'),
            array('name' => '中速快递','code' => 'zhongsukuaidi'),
            array('name' => '优能物流','code' => 'mantoo'),
            array('name' => '国美','code' => 'gomeorder'),
            array('name' => '亚马逊中国订单','code' => 'amazoncnorder'),
            array('name' => '蜜芽订单','code' => 'miaorder'),
            array('name' => '顺丰订单','code' => 'sfexpressorder'),
            array('name' => '申通快运','code' => 'stoe56'),
            array('name' => 'City-Link','code' => 'citylink'),
            array('name' => '德邦快运','code' => 'debangwuliu'),
            array('name' => '银捷速递','code' => 'yinjiesudi'),
            array('name' => 'D速快递','code' => 'dsukuaidi'),
            array('name' => '民邦速递','code' => 'minbangsudi'),
            array('name' => '百世快运','code' => 'baishiwuliu'),
            array('name' => 'DHL-德国件（DHL Deutschland）','code' => 'dhlde'),
            array('name' => '能装能送','code' => 'canhold'),
            array('name' => '聚美优品','code' => 'jumeiyoupinorder'),
            array('name' => '诚一物流','code' => 'parcelchina'),
            array('name' => '网易严选','code' => 'wangyiyxorder'),
            array('name' => '龙邦速递','code' => 'longbanwuliu'),
            array('name' => '明亮物流','code' => 'mingliangwuliu'),
            array('name' => '速尔快递','code' => 'suer'),
            array('name' => '盛辉物流','code' => 'shenghuiwuliu'),
            array('name' => '越丰物流','code' => 'yuefengwuliu'),
            array('name' => '比利时（Bpost）','code' => 'bpost'),
            array('name' => '韵达快递','code' => 'yunda'),
            array('name' => '唯品会','code' => 'vipshoporder'),
            array('name' => '美丽说','code' => 'meilishuoorder'),
            array('name' => '顺丰优选','code' => 'sfbestorder'),
            array('name' => '驼峰国际','code' => 'humpline'),
            array('name' => '小米订单','code' => 'xiaomiorder'),
            array('name' => '一智通','code' => '1ziton'),
            array('name' => 'TransRush','code' => 'transrush'),
            array('name' => '百世快递','code' => 'huitongkuaidi'),
            array('name' => '联昊通','code' => 'lianhaowuliu'),
            array('name' => '远成物流','code' => 'yuanchengwuliu'),
            array('name' => 'FedEx-美国件','code' => 'fedexus'),
            array('name' => 'OCS','code' => 'ocs'),
            array('name' => '巴西(Brazil Post/Correios)','code' => 'brazilposten'),
            array('name' => '孔夫子','code' => 'kongfzorder'),
            array('name' => '一号店','code' => 'yhdshoporder'),
            array('name' => '卷皮','code' => 'juanpiorder'),
            array('name' => '淘宝订单','code' => 'taobaoorder'),
            array('name' => '盛丰物流','code' => 'shengfengwuliu'),
            array('name' => '瑞典（Sweden Post）','code' => 'ruidianyouzheng'),
            array('name' => '新邦物流','code' => 'xinbangwuliu'),
            array('name' => '恒路物流','code' => 'hengluwuliu'),
            array('name' => '华夏龙','code' => 'huaxialongwuliu'),
            array('name' => '龙飞祥快递','code' => 'longfx'),
            array('name' => '城市映急','code' => 'city56'),
            array('name' => '顺心捷达','code' => 'sxjdfreight'),
            array('name' => '圆通承诺达','code' => 'ytchengnuoda'),
            array('name' => '宁夏万家通','code' => 'wanjiatong'),
            array('name' => '通道','code' => 'intercomv2'),
            array('name' => '曹操到','code' => 'sfpost'),
            array('name' => 'USPSCN','code' => 'uspscn'),
            array('name' => '跨境直邮通','code' => 'kjde'),
            array('name' => '美邦国际快递','code' => 'meibang'),
            array('name' => '快达物流','code' => 'kuaidawuliu'),
            array('name' => '昂威物流','code' => 'onway'),
            array('name' => '麦力快递','code' => 'mailikuaidi'),
            array('name' => '7号速递','code' => 'express7th'),
            array('name' => '五六快运','code' => '56kuaiyun'),
            array('name' => '速通物流','code' => 'sut56'),
            array('name' => '迅达速递','code' => 'xdexpress'),
            array('name' => '澳行快递','code' => 'desworks'),
            array('name' => '易邮速运','code' => 'yiyou'),
            array('name' => 'DHL HK','code' => 'dhlhk'),
            array('name' => '先锋国际快递','code' => 'pioneer'),
            array('name' => '黑猫速运','code' => 'heimao56'),
            array('name' => '快8速运','code' => 'kuai8'),
            array('name' => '东西E全运','code' => 'ecotransite'),
            array('name' => '燕文物流','code' => 'yw56'),
            array('name' => 'JDIEX','code' => 'jdiex'),
            array('name' => '泰捷达国际物流','code' => 'ztjieda'),
            array('name' => '捎客物流','code' => 'shaoke'),
            array('name' => '全球速递','code' => 'pdstow'),
            array('name' => '安达易国际速递','code' => 'adiexpress'),
            array('name' => '番薯国际货运','code' => 'koali'),
            array('name' => '贝贝','code' => 'beibeiorder'),
            array('name' => '德邦快递','code' => 'debangkuaidi'),
            array('name' => '联合速运','code' => 'unitedex'),
            array('name' => '龙邦物流','code' => 'lbex'),
            array('name' => '东方航空物流','code' => 'ealceair'),
            array('name' => '优莎速运','code' => 'eusacn'),
            array('name' => '?信物流WTO','code' => 'logistics'),
            array('name' => 'GHT物流','code' => 'ghtexpress'),
            array('name' => '香港伟豪国际物流','code' => 'whgjkd'),
            array('name' => '澳洲迈速快递','code' => 'maxeedexpress'),
            array('name' => 'TCXB国际物流','code' => 'tcxbthai'),
            array('name' => '贝业物流','code' => 'boyol'),
            array('name' => '如家国际快递','code' => 'homecourier'),
            array('name' => '东方汇','code' => 'est365'),
            array('name' => '八达通','code' => 'bdatong'),
            array('name' => '中骅物流','code' => 'chunghwa56'),
            array('name' => '潍鸿','code' => 'grivertek'),
            array('name' => '澳丰速递','code' => 'sfau'),
            array('name' => '环国运物流','code' => 'hgy56'),
            array('name' => '聚物物流','code' => 'juwu'),
            array('name' => '波音速递','code' => 'overseaex'),
            array('name' => '鑫远东速运','code' => 'xyd666'),
            array('name' => '中环快递','code' => 'zhonghuan'),
            array('name' => '沃埃家','code' => 'wowvip'),
            array('name' => 'OBOR Express','code' => 'oborexpress'),
            array('name' => '盛丰物流','code' => 'sfwl'),
            array('name' => '转运中国','code' => 'uszcn'),
            array('name' => '远航国际快运','code' => 'yuanhhk'),
            array('name' => '鼎润物流','code' => 'la911'),
            array('name' => '澳新物流','code' => 'axexpress'),
            array('name' => '高捷快运','code' => 'goldjet'),
            array('name' => 'GT国际快运','code' => 'gtgogo'),
            array('name' => '蓝弧快递','code' => 'lanhukuaidi'),
            array('name' => '速达通','code' => 'sdto'),
            array('name' => '苏豪快递','code' => 'shipsoho'),
            array('name' => '三盛快递','code' => 'sanshengco'),
            array('name' => '迅速快递','code' => 'xunsuexpress'),
            array('name' => '众川国际','code' => 'zhongchuan'),
            array('name' => '陆本速递 LUBEN EXPRESS','code' => 'luben'),
            array('name' => '西膺\\?','code' => 'seino'),
            array('name' => '加拿大联通快运','code' => 'fastontime'),
            array('name' => '花瓣转运','code' => 'flowerkd'),
            array('name' => '联通快递','code' => 'ltparcel'),
            array('name' => '鸿远物流','code' => 'hyeship'),
            array('name' => 'europeanecom','code' => 'europeanecom'),
            array('name' => '天美快递','code' => 'taimek'),
            array('name' => '合心速递','code' => 'hexinexpress'),
            array('name' => 'Highsince','code' => 'highsince'),
            array('name' => '蜜蜂速递','code' => 'bee001'),
            array('name' => '天使物流云','code' => 'tswlcloud'),
            array('name' => '王牌快递','code' => 'shipbyace'),
            array('name' => '华美快递','code' => 'hmus'),
            array('name' => '折800','code' => 'zhe800order'),
            array('name' => '小红书','code' => 'xiaohongshuorder'),
            array('name' => '铁中快运','code' => 'tzky'),
            array('name' => '景顺物流','code' => 'jingshun'),
            array('name' => '中环转运','code' => 'zhonghuanus'),
            array('name' => 'YCG物流','code' => 'ycgglobal'),
            array('name' => '驿递汇速递','code' => 'yidihui'),
            array('name' => 'track-parcel','code' => 'trackparcel')
        ]);
    }



}
